/*
Clinical Match API

A simple API to match patients to clinical trials.

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1ClinicalmatchPost400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ClinicalmatchPost400Response{}

// V1ClinicalmatchPost400Response struct for V1ClinicalmatchPost400Response
type V1ClinicalmatchPost400Response struct {
	Status *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewV1ClinicalmatchPost400Response instantiates a new V1ClinicalmatchPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ClinicalmatchPost400Response() *V1ClinicalmatchPost400Response {
	this := V1ClinicalmatchPost400Response{}
	return &this
}

// NewV1ClinicalmatchPost400ResponseWithDefaults instantiates a new V1ClinicalmatchPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ClinicalmatchPost400ResponseWithDefaults() *V1ClinicalmatchPost400Response {
	this := V1ClinicalmatchPost400Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ClinicalmatchPost400Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ClinicalmatchPost400Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ClinicalmatchPost400Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ClinicalmatchPost400Response) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V1ClinicalmatchPost400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ClinicalmatchPost400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V1ClinicalmatchPost400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V1ClinicalmatchPost400Response) SetMessage(v string) {
	o.Message = &v
}

func (o V1ClinicalmatchPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ClinicalmatchPost400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableV1ClinicalmatchPost400Response struct {
	value *V1ClinicalmatchPost400Response
	isSet bool
}

func (v NullableV1ClinicalmatchPost400Response) Get() *V1ClinicalmatchPost400Response {
	return v.value
}

func (v *NullableV1ClinicalmatchPost400Response) Set(val *V1ClinicalmatchPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ClinicalmatchPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ClinicalmatchPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ClinicalmatchPost400Response(val *V1ClinicalmatchPost400Response) *NullableV1ClinicalmatchPost400Response {
	return &NullableV1ClinicalmatchPost400Response{value: val, isSet: true}
}

func (v NullableV1ClinicalmatchPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ClinicalmatchPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


