/*
Clinical Match API

A simple API to match patients to clinical trials.

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1ClinicalmatchPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ClinicalmatchPost200Response{}

// V1ClinicalmatchPost200Response struct for V1ClinicalmatchPost200Response
type V1ClinicalmatchPost200Response struct {
	Status *string `json:"status,omitempty"`
	Matches []V1ClinicalmatchPost200ResponseMatchesInner `json:"matches,omitempty"`
}

// NewV1ClinicalmatchPost200Response instantiates a new V1ClinicalmatchPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ClinicalmatchPost200Response() *V1ClinicalmatchPost200Response {
	this := V1ClinicalmatchPost200Response{}
	return &this
}

// NewV1ClinicalmatchPost200ResponseWithDefaults instantiates a new V1ClinicalmatchPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ClinicalmatchPost200ResponseWithDefaults() *V1ClinicalmatchPost200Response {
	this := V1ClinicalmatchPost200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1ClinicalmatchPost200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ClinicalmatchPost200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1ClinicalmatchPost200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1ClinicalmatchPost200Response) SetStatus(v string) {
	o.Status = &v
}

// GetMatches returns the Matches field value if set, zero value otherwise.
func (o *V1ClinicalmatchPost200Response) GetMatches() []V1ClinicalmatchPost200ResponseMatchesInner {
	if o == nil || IsNil(o.Matches) {
		var ret []V1ClinicalmatchPost200ResponseMatchesInner
		return ret
	}
	return o.Matches
}

// GetMatchesOk returns a tuple with the Matches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ClinicalmatchPost200Response) GetMatchesOk() ([]V1ClinicalmatchPost200ResponseMatchesInner, bool) {
	if o == nil || IsNil(o.Matches) {
		return nil, false
	}
	return o.Matches, true
}

// HasMatches returns a boolean if a field has been set.
func (o *V1ClinicalmatchPost200Response) HasMatches() bool {
	if o != nil && !IsNil(o.Matches) {
		return true
	}

	return false
}

// SetMatches gets a reference to the given []V1ClinicalmatchPost200ResponseMatchesInner and assigns it to the Matches field.
func (o *V1ClinicalmatchPost200Response) SetMatches(v []V1ClinicalmatchPost200ResponseMatchesInner) {
	o.Matches = v
}

func (o V1ClinicalmatchPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ClinicalmatchPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Matches) {
		toSerialize["matches"] = o.Matches
	}
	return toSerialize, nil
}

type NullableV1ClinicalmatchPost200Response struct {
	value *V1ClinicalmatchPost200Response
	isSet bool
}

func (v NullableV1ClinicalmatchPost200Response) Get() *V1ClinicalmatchPost200Response {
	return v.value
}

func (v *NullableV1ClinicalmatchPost200Response) Set(val *V1ClinicalmatchPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ClinicalmatchPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ClinicalmatchPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ClinicalmatchPost200Response(val *V1ClinicalmatchPost200Response) *NullableV1ClinicalmatchPost200Response {
	return &NullableV1ClinicalmatchPost200Response{value: val, isSet: true}
}

func (v NullableV1ClinicalmatchPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ClinicalmatchPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


