/*
Clinical Match API

A simple API to match patients to clinical trials.

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ClinicalmatchPostRequestLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ClinicalmatchPostRequestLocation{}

// V1ClinicalmatchPostRequestLocation The geographic location of the patient encounter.
type V1ClinicalmatchPostRequestLocation struct {
	// The latitude of the location.
	Latitude float32 `json:"latitude"`
	// The longitude of the location.
	Longitude float32 `json:"longitude"`
}

type _V1ClinicalmatchPostRequestLocation V1ClinicalmatchPostRequestLocation

// NewV1ClinicalmatchPostRequestLocation instantiates a new V1ClinicalmatchPostRequestLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ClinicalmatchPostRequestLocation(latitude float32, longitude float32) *V1ClinicalmatchPostRequestLocation {
	this := V1ClinicalmatchPostRequestLocation{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewV1ClinicalmatchPostRequestLocationWithDefaults instantiates a new V1ClinicalmatchPostRequestLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ClinicalmatchPostRequestLocationWithDefaults() *V1ClinicalmatchPostRequestLocation {
	this := V1ClinicalmatchPostRequestLocation{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *V1ClinicalmatchPostRequestLocation) GetLatitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *V1ClinicalmatchPostRequestLocation) GetLatitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *V1ClinicalmatchPostRequestLocation) SetLatitude(v float32) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *V1ClinicalmatchPostRequestLocation) GetLongitude() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *V1ClinicalmatchPostRequestLocation) GetLongitudeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *V1ClinicalmatchPostRequestLocation) SetLongitude(v float32) {
	o.Longitude = v
}

func (o V1ClinicalmatchPostRequestLocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ClinicalmatchPostRequestLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	return toSerialize, nil
}

func (o *V1ClinicalmatchPostRequestLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"latitude",
		"longitude",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ClinicalmatchPostRequestLocation := _V1ClinicalmatchPostRequestLocation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ClinicalmatchPostRequestLocation)

	if err != nil {
		return err
	}

	*o = V1ClinicalmatchPostRequestLocation(varV1ClinicalmatchPostRequestLocation)

	return err
}

type NullableV1ClinicalmatchPostRequestLocation struct {
	value *V1ClinicalmatchPostRequestLocation
	isSet bool
}

func (v NullableV1ClinicalmatchPostRequestLocation) Get() *V1ClinicalmatchPostRequestLocation {
	return v.value
}

func (v *NullableV1ClinicalmatchPostRequestLocation) Set(val *V1ClinicalmatchPostRequestLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ClinicalmatchPostRequestLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ClinicalmatchPostRequestLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ClinicalmatchPostRequestLocation(val *V1ClinicalmatchPostRequestLocation) *NullableV1ClinicalmatchPostRequestLocation {
	return &NullableV1ClinicalmatchPostRequestLocation{value: val, isSet: true}
}

func (v NullableV1ClinicalmatchPostRequestLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ClinicalmatchPostRequestLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


